### ISSUE TITLE
FastScroller#getScrollProportion method returns Infinity

### ISSUE THREAD

**Issue by siempredelao** [L4Digital/FastScroll#18]
I'm using a _FastScrollRecyclerView_ inside a _DialogFragment_ and whenever I manually scroll down, the thumb goes down to the bottom and sticks to the bottom. I have discovered that the problem comes from the `FastScroller#getScrollProportion`. Let me explain why:
``` java
final int verticalScrollOffset = recyclerView.computeVerticalScrollOffset(); // verticalScrollOffset == 120
final int verticalScrollRange = recyclerView.computeVerticalScrollRange(); // verticalScrollRange == 400
float proportion = (float) verticalScrollOffset / ((float) verticalScrollRange - mHeight); // mHeight == 400, proportion = 120 / 0 = Infinity
return mHeight * proportion; // returns Infinity
```

I will try to create a PR whenever I have some free time ;)

**Comment by randr0id** [comment]
If `verticalScrollRange` and `mHeight` are equal, then `FastScroller#getScrollProportion` shouldn't be called because there is nothing to scroll.

However, if they are the same it results in a divide by zero error. I will push a fix to divide by 1 if that occurs, which should fix the infinity error you're seeing.

**Comment by randr0id** [comment]
Fixed in commit f78732a and released in 1.0.4

**Comment by kingsleyadio** [comment]
This is still a problem unfortunately.
I was able to reproduce the snapping to bottom issue on version 1.1.2.

We can't use 2.0.0 as we haven't migrated to AndroidX just yet. But I imagine the problem still persists.
